# Should hold common configuration between the beta and the production server
imageRepository: "775662142440.dkr.ecr.eu-west-1.amazonaws.com/devops-league"

web:
  replicas: 1
  command:
    - "/usr/local/bin/uwsgi"
  commandArgs:
    - "--ini"
    - "./uwsgi.ini"
  containerPort: 8080
  requestsCpu: 100m
  requestsMemory: 200Mi
  limitsCpu: 500m
  limitsMemory: 500Mi

worker:
  command:
    - "celery"
  commandArgs:
    - "--app=txsentinel.celery_worker.celery_client"
    - "worker"
    - "--loglevel=INFO"
  replicas: 1
  requestsCpu: 100m
  requestsMemory: 200Mi
  limitsCpu: 500m
  limitsMemory: 500Mi

config:
  SECRETS_PATH: "/etc/secrets-volume"
  GITHUB_ORGANIZATION: "transifex"
  GITHUB_USER: "wyngarde"
  GITHUB_DEPLOY_HEAD: "devel"
  GITHUB_DEPLOY_BASE: "master"
  GITHUB_STALE_IGNORE_BRANCHES: "master,base,devel,beta,readonly"

secrets:
  github-token: GITHUB_TOKEN
  github-webhook-secret: GITHUB_WEBHOOK_SECRET
  secret-key: SECRET_KEY
  slack-signing-secret: SLACK_SIGNING_SECRET

ingress:
  certificateArns:
  - arn:aws:acm:eu-west-1:775662142440:certificate/2c3f7899-dbba-48ae-bcf3-7727b7970279
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /health
    alb.ingress.kubernetes.io/load-balancer-attributes: idle_timeout.timeout_seconds=180
  hostNames:
    - devops-league.svc.transifex.net
